ALC-119 - include token price in pool metrics
alchemistcoin/copper pull request #10
Opened 2021-04-22 16:21 UTC by hosainnet

When querying pool metrics from graphql, include tokenAmountIn and tokenAmountOut in the response

Dividing tokenAmountIn by tokenAmountOut give us the price at each metric point

Also fixed test warning when React components are re-rendered

- [ ] Branch name corresponds to Linear ticket number.
- [ ] Added sufficient integration and unit tests.
- [ ] Addressed a single concern in the least number of changed lines as
      possible.
- [ ] Only fixed/added the functionality in question **OR** address wide-spread
      whitespace/style issues, not both.

2021-04-22 16:21 UTC, hosainnet commented on src/components/PoolsList/index.test.tsx
> +import { act, render, screen } from "@testing-library/react";
See https://reactjs.org/docs/test-utils.html#act

2021-04-22 16:43 UTC, moldovanflorin93 commented on src/components/PoolsList/index.test.tsx
> +    await new Promise((resolve) => setTimeout(resolve, 0)); // wait for response
if you think it helps, you can have a function:
`async function wait(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}
`
and everywhere you need it, you just call it: 
`await wait(0);`

2021-04-22 16:50 UTC, moldovanflorin93 commented on src/types/PoolMetrics.ts
> +export type PoolMetric = {
Do you think it would help you to have some models that can validate their fields? I'm thinking of modules like
class-transformer and class-validator ?

2021-04-22 16:54 UTC, moldovanflorin93 commented on src/utils/metrics.test.ts
> +test("Maps metrics response to ", () => {
do you think you should make also a test where metric_1234.length >= 2 ?

2021-04-22 17:13 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +  for (let metricKey in metrics) {
I was just wondering if this for would work like this (it seems simpler):
```suggestion
  for (let metricKey of metrics) {
        result[metricKey] = [];
        
        if (metricKey) {
          result[metricKey] = [
            {
              poolLiquidity: metricKey.poolLiquidity,
              poolTotalSwapFee: metricKey.poolTotalSwapFee,
              poolTotalSwapVolume: metricKey.poolTotalSwapVolume,
              price:
                metricKey.tokenAmountIn /
                metricKey.tokenAmountOut,
            }
          ];
        }
      }
```

2021-04-23 06:32 UTC, moldovanflorin93 commented on src/constants/index.ts
> +  },
I was wondering why you need both constans, TOKEN_SYMBOLS_TO_ADDRESS and TOKEN_ADDRESS_TO_SYMBOL?
wouldn't that be enough just to have TOKEN_SYMBOLS_TO_ADDRESS? Then just use Object.keys / Object.values everywhere you need it.

2021-04-23 06:46 UTC, moldovanflorin93 commented on src/constants/index.ts
>    ALLOWED_POOL_TOKENS: ["WETH", "DAI", "USDC"],
every time you add a new token, you will have to add it in ALLOWED_POOL_TOKENS as well. Constant ALLOWED_POOL_TOKENS it is in fact Object.values(TOKEN_SYMBOLS_TO_ADDRESS), right?. Do you think it would be better to just use Object.values(TOKEN_SYMBOLS_TO_ADDRESS) everywhere instead of having ALLOWED_POOL_TOKENS  constant?
Or you can do something like that:
```suggestion
  export NETWORK = { ...networkConfig };
  export TOKEN_SYMBOLS_TO_ADDRESS = {
    WETH: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    DAI: "0x6b175474e89094c44da98b954eedeac495271d0f",
    USDC: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
  };
  export ALLOWED_POOL_TOKENS = Object.keys(TOKEN_SYMBOLS_TO_ADDRESS );
```

2021-04-23 06:48 UTC, moldovanflorin93 commented on src/queries/test/graphql-requests.ts
> +        id_in: [
If you think it helps:
```suggestion
        id_in: Object.values(TOKEN_SYMBOLS_TO_ADDRESS)
```

2021-04-23 06:56 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +  token: string,
do you think token 'tokenAddress' is a better name for this param?

2021-04-23 06:57 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +  if (token == constants.TOKEN_SYMBOLS_TO_ADDRESS["WETH"]) {
Maybe, you can use Strict equality ( === ).

2021-04-23 07:03 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +      let metric = metrics[metricKey][0];
I'm trying to understand.
So each metric is an array with a single element?
If yes, why not a simple object.

2021-04-23 10:49 UTC, hosainnet commented on src/components/PoolsList/index.test.tsx
> +    await new Promise((resolve) => setTimeout(resolve, 0)); // wait for response
Done 👍

2021-04-23 10:50 UTC, hosainnet commented on src/utils/metrics.ts
> +  for (let metricKey in metrics) {
I don't think this works because the raw data comes in as an object so we're iterating through the keys 
<img width="756" alt="Screenshot 2021-04-23 at 11 28 47" src="https://user-images.githubusercontent.com/629600/115860887-0be3eb00-a42a-11eb-890b-8a0d6bb2f505.png">

2021-04-23 10:51 UTC, hosainnet commented on src/queries/test/graphql-requests.ts
> +        id_in: [
I used the hardcoded values to make sure we're aware that those have changed (in case we changed them incorrectly) but happy to consider this, what do you think?

2021-04-23 10:51 UTC, hosainnet commented on src/utils/metrics.ts
> +  token: string,
Done 👍

2021-04-23 10:51 UTC, hosainnet commented on src/utils/metrics.ts
> +  if (token == constants.TOKEN_SYMBOLS_TO_ADDRESS["WETH"]) {
👍

2021-04-23 11:12 UTC, hosainnet commented on src/utils/metrics.ts
> +      let metric = metrics[metricKey][0];
Updated 👍

2021-04-23 18:28 UTC, moldovanflorin93 commented on src/components/PoolsList/index.test.tsx
> +async function waitForResponse() {
:+1:

2021-04-23 18:33 UTC, moldovanflorin93 commented on src/queries/test/graphql-requests.ts
> +        id_in: [
I think it is a good ideea.

2021-04-23 18:35 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +  tokenAddress: string,
:+1:

2021-04-23 19:09 UTC, moldovanflorin93 commented on src/utils/metrics.ts
> +  for (let metricKey in metrics) {
aahh sorry, you are right.
`for (const [key, value] of Object.entries(metrics)) {...}`
This should work (I hope :pray: )

2021-04-24 06:51 UTC, pygeek requested changes
Looks good for the most part just a few suggestions around relative vs absolute imports. and `.map` over `for of`. Also, consider avoiding overuse of jsonToGraphQLQuer—I'd only use it when needing to programmatically needing to build a query.

2021-04-24 06:51 UTC, pygeek commented on src/queries/prices.test.ts
> +import { TOKEN_PRICES_REQUEST } from "./test/graphql-requests";
see: https://github.com/alchemistcoin/copper/pull/11 . once merged in you should be able to just import `test/graphql-requests`. you no longer need the ./ for imports—instead just do absolute imports.

2021-04-24 06:51 UTC, pygeek commented on src/queries/prices.ts
> +import constants from "../constants";
see: https://github.com/alchemistcoin/copper/pull/11 . once merged in you should be able to just import `test/graphql-requests`. you no longer need the ../ for imports—instead just do absolute imports.

2021-04-24 06:51 UTC, pygeek commented on src/utils/metrics.ts
> +} from "../types/PoolMetrics";
see: https://github.com/alchemistcoin/copper/pull/11 . once merged in you should be able to just import `test/graphql-requests`. you no longer need the ../ for imports—instead use absolute imports (url types/PoolMetrics)

2021-04-24 06:51 UTC, pygeek commented on src/utils/metrics.ts
> +  for (let metricKey in metrics) {
It's generally recommended in es6+ (and I think typescript as well) to iterate using `.map` for reasons around immutability and chaining. https://github.com/airbnb/javascript#iterators-and-generators

2021-04-24 06:51 UTC, pygeek commented on src/queries/prices.ts
> +export const getTokenPrices = () => {
If possible I would just write normal graphQL here since you aren't doing anything special to build the query.

2021-04-24 09:52 UTC, hosainnet commented on src/utils/metrics.ts
> +} from "../types/PoolMetrics";
You mean `queries/test/graphql-requests` right? unless you're suggesting to have a common `src/test` folder

2021-04-24 10:54 UTC, hosainnet commented on src/queries/prices.ts
> +import constants from "../constants";
How do you deal when there is a clash between the folder name and another module? 

![Screenshot 2021-04-24 at 11 54 01](https://user-images.githubusercontent.com/629600/115956261-c4c22c80-a4f3-11eb-8904-28e32ab9962c.png)

2021-04-24 11:06 UTC, hosainnet commented on src/queries/prices.ts
> +export const getTokenPrices = () => {
Yeah I tried that, e.g
```
{
  tokenPrices(where: {id_in: $allowedTokens}) {
    id
    price
    symbol
  }
}
```

And passing an allowedTokens in `useQuery` but could not get it work. I figured doing it this way means we don't need to pass the allowed tokens everytime we use this query

2021-04-24 11:30 UTC, hosainnet commented on src/constants/index.ts
>    ALLOWED_POOL_TOKENS: ["WETH", "DAI", "USDC"],
Done 👍

2021-04-24 11:32 UTC, hosainnet commented on src/constants/index.ts
> +  },
In one place where we do currency conversion, we need to look up WETH address https://github.com/alchemistcoin/copper/pull/10/files#diff-ce3a93efd046e7a95d61484997047a9987f83e8947ca7abfdd6f3669cfed455eR48 so it's nice to have the other map for reverse lookup

2021-04-24 14:09 UTC, hosainnet commented on src/utils/metrics.ts
> +  for (let metricKey in metrics) {
👍

2021-04-24 14:15 UTC, hosainnet commented on tsconfig.json
> +    "baseUrl": "src",
Needed for absaloute path IDE support https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000613964-Typescript-How-to-auto-import-with-absolute-paths-if-baseUrl-is-set-in-tsconfig-json

2021-04-24 14:31 UTC, pygeek approved these changes

2021-04-24 14:32 UTC, merged