Poke weights historical data for a pool
alchemistcoin/copper pull request #13
Opened 2021-04-25 00:43 UTC by ledes

- [x] Retrieve weight change data for a token in any given LBP on Balancer containing a tokenList of length 2 and the gradual weight change setting enabled. Need time series of:

- [x] timestamp

- [x] new weights for the tokens in the pool (knowing start weights and desired end weights is required for this)

- We'll need etherscan api keys for local and prod

Example of use:

```

  let pokeWeightTx = [];
  getPoolTransations("0xbd578f7afcc3e4ac8266334d6d165e8c75fdd518").then(
    (tx) => {
      pokeWeightTx = filterPokeWeightsTnx(tx);
    }
  );

```

2021-04-25 01:22 UTC, hosainnet commented on src/constants/network/index.ts
> +        etcan: "xxxx", // todo add
Can we read this from an env variable please? example: https://github.com/alchemistcoin/copper/pull/12/files#diff-d35cb152a57be312f789c363a6cd89b905b31b910ee141ae1f69612eba9e3050R5
also maybe etherscanUrl or something makes more sense as the key?

2021-04-25 01:22 UTC, hosainnet commented on src/utils/pools.test.ts
> +} from "./mocks/pools";
The new way for imports is `utils/pools` and `utils/pools/mocks`

2021-04-25 01:22 UTC, hosainnet commented on src/utils/pools.test.ts
> +  expect(pokeWeightTransactions.length).toBe(1);
We should also assert that transaction[0].data === "0xe211b875"

2021-04-25 22:50 UTC, ledes commented on src/constants/network/index.ts
> +        etcan: "xxxx", // todo add
yeah! I was trying to be clever with the name so it is not obvious, but maybe I took it too far 😄

2021-04-25 23:09 UTC, hosainnet commented on src/services/poolService.ts
> +  );
Minor: we can probably create a provider outside of the function so that we don't create one everytime every time we call getPoolTransactions

2021-04-26 07:32 UTC, pygeek requested changes

2021-04-26 07:32 UTC, pygeek commented on src/utils/mocks/pools.ts
> +export const allPoolsTransactions = [
I think the convention is `__mocks__`. If you use this naming scheme the mock/fixture will be imported automatically.
See: https://stackoverflow.com/questions/65108082/jest-manual-mocks-does-not-use-mock-file-in-cra

2021-04-26 07:32 UTC, pygeek commented on src/services/poolService.ts
> +  );
This is a good example of where a class may be beneficial, the constructor of the pool service would do this setup once and assign it to an instance variable. Technically, I believe this file should be called EtherscanService, and this method should be called getTransactions. As all it is doing is getting transactions for an address.

2021-04-26 07:32 UTC, pygeek commented on src/constants/index.ts
> +  POKE_WEIGHT_METHOD_ID: "0xe211b875",
POKE_WEIGHT_FRAGMENT_NAME = "pokeWeights"
Would it be possible to use the human readable ABI fragment name instead?  We can use ethers.interface.parseTransaction(tx).name in pools.ts to do this.

We'll likely need the balancer ABI in our repository at some point anyway. Consider placing it under `src/constants/balancer/abi.ts`—it's located here: https://github.com/balancer-labs/pool-management-vue/blob/d03939af8c9136be58e7c1b95fabfe0bb6c9c502/src/helpers/abi/ConfigurableRightsPool.json

in pools.ts
instantiate interface using the balancer ABI `interface = new ethers.utils.Interface(<balancer abi>);`

2021-04-26 07:33 UTC, pygeek commented
A couple feedback items, but looks good overall. Also see comments regarding commit naming in other pr.

2021-04-26 07:35 UTC, CryptoOsanu commented on src/utils/pools.ts
>      )
I know you haven't changed these conditions but I'm trying to understand them.
indexOf returns the first index at which a given element can be found in the array, or -1 if it is not present. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
so, why are lines 21 and 22 necessary?

2021-04-27 00:26 UTC, ledes commented on src/utils/pools.ts
>      )
We are using indexOf to  know if one of the icons is included in allowed_token_symbols.

Like 18 and 19 checks that there is one of the 2 tokens  included. 
Like 21 and 22 checks that both of them are not included at the same time

2021-04-27 00:42 UTC, ledes commented on src/services/poolService.ts
> +  );
I created a new service as a class. Let me know if it makes sense

2021-04-27 00:43 UTC, ledes commented on src/constants/index.ts
> +  POKE_WEIGHT_METHOD_ID: "0xe211b875",
I messaged you on  discord but trying this was giving me an error for some transactions. There may be an easy solution but I wasn't sure:

```
const crpAbi = require("constants/balancer/abi/ConfigurableRightsPool.json");

const balancerInterface = new ethers.utils.Interface(crpAbi.abi);

export const filterPokeWeightsTnx = (poolTransactions: Array<Transaction>) => {
  return poolTransactions.filter((tnx: Transaction) => {
    console.log(tnx);
    const a = balancerInterface.parseTransaction(tnx);

    console.log(a);
    return tnx.data === constants.POKE_WEIGHT_METHOD_ID;
  });
};
```

2021-04-28 01:28 UTC, pygeek commented
@ledes Let's chat offline regarding this PR when you're free so we can get this merged in.

2021-04-29 13:24 UTC, hosainnet approved these changes

2021-04-29 23:33 UTC, merged