Alc 199 page structure
alchemistcoin/copper pull request #16
Opened 2021-04-26 00:39 UTC by ledes

Basic structure of page 

https://user-images.githubusercontent.com/12192218/116015124-430ef380-a606-11eb-9ea0-2ee4c3fb4392.mov

2021-04-26 07:09 UTC, pygeek requested changes
Looks good just fix failing test. Also, I notice a lot of your commits are ambiguous/non-descriptive "d" that make it into main branch—you may want to clean those up before code reviews / merging into main. Also, note your imports no longer require "./" use absolute imports instead (with the exception of constants.ts—this will be fixed in a future PR).

2021-04-26 09:56 UTC, nuurcodes commented on src/pages/PoolDashboard/index.tsx
> +    <Wrap spacing="30px">
You could use `Grid` or `SimpleGrid` from Chakra UI instead of `Wrap`

[Grid](https://chakra-ui.com/docs/layout/grid)
[SimpleGrid](https://chakra-ui.com/docs/layout/simple-grid)

2021-04-27 00:58 UTC, ledes commented on src/pages/PoolDashboard/index.tsx
> +    <Wrap spacing="30px">
you are a beast! Thanks!

2021-04-27 01:03 UTC, ledes commented
> Looks good just fix failing test. Also, I notice a lot of your commits are ambiguous/non-descriptive "d" that make it into main branch—you may want to clean those up before code reviews / merging into main. Also, note your imports no longer require "./" use absolute imports instead (with the exception of constants.ts—this will be fixed in a future PR).

Yeah sorry about that. I'm used to don't have to  pay attention to  commit messages but I'll  be careful on this repo.
I'd rather not mess with the current history, but I'll add regular messages after this if that works

2021-04-27 01:10 UTC, hosainnet commented
> > Looks good just fix failing test. Also, I notice a lot of your commits are ambiguous/non-descriptive "d" that make it into main branch—you may want to clean those up before code reviews / merging into main. Also, note your imports no longer require "./" use absolute imports instead (with the exception of constants.ts—this will be fixed in a future PR).
> 
> Yeah sorry about that. I'm used to don't have to pay attention to commit messages but I'll be careful on this repo.
> I'd rather not mess with the current history, but I'll add regular messages after this if that works

No need to mess with history, just use the Squash option when you merge this one and edit the message to have a brief summary :)
<img width="421" alt="Screenshot 2021-04-27 at 02 08 35" src="https://user-images.githubusercontent.com/629600/116169888-9617a200-a6fd-11eb-9c33-f87c66d87f39.png">

2021-04-27 01:12 UTC, hosainnet submitted a review, later dismissed

2021-04-28 00:43 UTC, hosainnet approved these changes

2021-04-28 00:55 UTC, merged