Alc 97
alchemistcoin/copper pull request #25
Opened 2021-05-04 18:20 UTC by macroman321

Please ensure have read our (contribution guidelines](CONTRIBUTING.md) and your
pull request adheres to the following guidelines:

- [ ] Branch name corresponds to Linear ticket number.
- [ ] Added sufficient integration and unit tests.
- [ ] Addressed a single concern in the least number of changed lines as
      possible.
- [ ] Only fixed/added the functionality in question **OR** address wide-spread
      whitespace/style issues, not both.

Thanks!

2021-05-04 18:56 UTC, jamespfarrell reviewed
Looks good besides the use of classes, but I guess Recharts may be forcing this decision?

2021-05-04 18:56 UTC, jamespfarrell commented on src/components/TopTokenHolders/index.tsx
> +class TopTokenHolders extends React.Component {
Have you tried out React hooks, or is there a reason you're going for classes?

2021-05-05 08:16 UTC, pygeek commented on src/components/TopTokenHolders/index.tsx
> +TopTokenHolders.propTypes = {
I believe we don't need prop types, since we already have an interface.

2021-05-05 08:17 UTC, jamespfarrell approved these changes
Looks good

2021-05-05 08:17 UTC, pygeek commented on src/services/EthplorerService.ts
> +    "https://api.ethplorer.io/getTopTokenHolders/0x88acdd2a6425c3faae4bc9650fd7e27e0bebb7ab?apiKey=EK-i88cm-MSc8YqU-bwY7A&limit=100"
consider placing this in constants and with string interpolation for address

2021-05-05 08:17 UTC, pygeek commented on src/services/EthplorerService.ts
> +    // @ts-ignore
Is there a reason to keep this ignore statement?

2021-05-05 08:20 UTC, pygeek commented on src/services/EthplorerService.ts
> +    response.holders.forEach((holder: { address: any; share: any }) => {
consider using .map instead

2021-05-05 08:22 UTC, pygeek commented on src/services/EthplorerService.ts
> +  let googleChartData = [];
Is there a reason why this is called "google"ChartData?

2021-05-05 08:23 UTC, pygeek commented on src/services/EthplorerService.ts
> +  let googleChartData = [];
Use const

2021-05-05 08:24 UTC, pygeek commented on src/components/TopTokenHolders/index.tsx
> +import { Chart } from "react-google-charts";
is there a reason why we used this instead of Recharts?

2021-05-05 08:25 UTC, pygeek reviewed
Looks good for the most part, just a few feedback items/questions.

2021-05-05 10:25 UTC, pygeek commented
I believe you still have a failing test.

2021-05-05 10:29 UTC, pygeek requested changes

2021-05-05 10:29 UTC, pygeek commented on src/services/EthplorerService.ts
> +    constants.network.ethplorerUrl +
PS: I meant just creating add constant with entire url using %s string interpolation.

2021-05-05 10:29 UTC, pygeek commented on src/components/TopTokenHolders/index.tsx
> +TopTokenHolders.propTypes = {
Think you can remove this and the import of prop-types.

2021-05-06 10:30 UTC, pygeek approved these changes

2021-05-06 11:36 UTC, pygeek approved these changes

2021-05-06 11:38 UTC, merged