Alc 300 swpa history
alchemistcoin/copper pull request #27
Opened 2021-05-05 17:14 UTC by hosainnet

Please ensure have read our (contribution guidelines](CONTRIBUTING.md) and your
pull request adheres to the following guidelines:

- [ ] Branch name corresponds to Linear ticket number.
- [ ] Added sufficient integration and unit tests.
- [ ] Addressed a single concern in the least number of changed lines as
      possible.
- [ ] Only fixed/added the functionality in question **OR** address wide-spread
      whitespace/style issues, not both.

Thanks!

2021-05-05 17:24 UTC, hosainnet commented on src/components/RightPanel/index.tsx
> -
Moved this fetching logic to parent component and pass props in

2021-05-05 17:42 UTC, hosainnet commented on src/pages/PoolDashboard/index.tsx
> +   */
Moved from above

2021-05-05 17:44 UTC, hosainnet commented on src/pages/PoolDashboard/index.tsx
> +   */
This is where we fetch the swap history

2021-05-05 17:44 UTC, hosainnet commented on src/utils/metrics.ts
> -}
Moved to price util to be re-used

2021-05-05 18:34 UTC, jamespfarrell requested changes

2021-05-05 18:34 UTC, jamespfarrell commented on src/queries/swap.ts
> +      orderByDirection: desc
I believe the api syntax is:
```
orderDirection: desc
```
not 
```
orderByDirection: desc
```

2021-05-05 22:24 UTC, ledes submitted a review, later dismissed

2021-05-05 22:24 UTC, ledes commented on src/components/SwapHistory/index.tsx
> +                  href={`https://etherscan.io/tx/${getTxHashFromId(swap.id)}`}
minor but you can have a const with `https://etherscan.io/` and reuse it

2021-05-05 23:56 UTC, hosainnet commented on src/queries/swap.ts
> +      orderByDirection: desc
Thanks 👍

2021-05-05 23:56 UTC, hosainnet commented on src/components/SwapHistory/index.tsx
> +                  href={`https://etherscan.io/tx/${getTxHashFromId(swap.id)}`}
👍

2021-05-06 00:17 UTC, ledes approved these changes

2021-05-06 00:17 UTC, ledes commented on src/components/SwapHistory/index.tsx
> +export default function Index({ swapHistory, launchToken }: SwapProps) {
you want to name the function like the name of the component. 
For this case `export default function SwapHistory(...`

2021-05-06 00:29 UTC, hosainnet commented on src/components/SwapHistory/index.tsx
> +export default function Index({ swapHistory, launchToken }: SwapProps) {
@ledes is it okay to update in the next PR?

2021-05-06 01:20 UTC, hosainnet commented on src/components/SwapHistory/index.tsx
> +export default function Index({ swapHistory, launchToken }: SwapProps) {
Done 👍

2021-05-06 11:23 UTC, pygeek commented on src/utils/token.test.ts
> +test("WETH, USDC and DAI are fund tokens", () => {
will approve this, but in future try to keep to one expect per test.

2021-05-06 11:24 UTC, pygeek commented on src/utils/price.ts
> +export function convertCurrency(
test this

2021-05-06 11:25 UTC, pygeek approved these changes
Approved and merging, we can address my comments in a separate ticket if necessary.

2021-05-06 11:25 UTC, merged